version: "3.8"

services:
  redis:
    image: redis:7
    container_name: yantrahack25-ml-redis
    ports:
      - "6380:6380"
    command: redis-server --port 6380
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  celery-worker:
    build:
      context: .
      dockerfile: celery.DockerFile
    container_name: yantrahack25-ml-celery-worker
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=redis://redis:6380/0
      - CELERY_RESULT_BACKEND=redis://redis:6380/0
